### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by Burkino** [h0nde/xrequests#1]
Is there any way to add support for proxies without needing to link to rotating proxy provider?
Instead of doing `proxies={'https': 'https://proxyserver.com'}` to instead do `proxies={'https': ['ip:port', 'ip:port']}` ?
If not, is there a way to set up a local rotating proxy server that gets ips from a file?

**Comment by h0nde** [comment]
```
import itertools
import xrequests

with open("proxies.txt") as fp:
    proxies = itertools.cycle(fp.read().splitlines())

for _ in range(5):
    proxy = next(proxies)
    client = xrequests.Session(proxies={"https": f"https://{proxy}"})
    print(f"Created client for {proxy}")
```

**Comment by FeelsBadMan1** [comment]
Hi, just a simple question regarding proxies:
How should i format proxies that use username and password login? i think its following format but im not sure:
username:password@ipadress:port

**Comment by FeelsBadMan1** [comment]
Hello, this code you just sent is not working. it select the first proxy in the list everytime and not goes to the next ones
